package com.minhhnn18898.trip_data.repo.trip_info

enum class DefaultCoverElement(val type: Int) {
    COVER_DEFAULT_THEME_SPRING(1),
    COVER_DEFAULT_THEME_SUMMER(2),
    COVER_DEFAULT_THEME_AUTUMN(3),
    COVER_DEFAULT_THEME_WINTER(4),
    COVER_DEFAULT_THEME_BEACH(5),
    COVER_DEFAULT_THEME_MOUNTAIN(6),
    COVER_DEFAULT_THEME_AURORA(7),
    COVER_DEFAULT_THEME_VIETNAM (8),
    COVER_DEFAULT_THEME_CHINA (9),
    COVER_DEFAULT_THEME_SEA_DIVING (10),
}